### ISSUE TITLE
Codacy integration

### ISSUE THREAD

**Issue by bereczdaniel** [bereczdaniel/Remindly#1]
Register this projects on Codacy.com

**Comment by bereczdaniel** [comment]
Project is registered: https://www.codacy.com/app/bereczdaniel/Remindly/dashboard
There is a wiki page for it.

**Comment by bereczdaniel** [comment]
Next time we should make a pull request for it. For now all of the _* refactor_ commits are for this issue.

**Comment by bereczdaniel** [comment]
@DanLszl please review it.

**Comment by DanielLaszlo** [comment]
@bereczdaniel On the wiki page, please create a section about the steps that were taken for the integration with Codacy.

**Comment by bereczdaniel** [comment]
@DanLszl done, check it

**Comment by micskeiz** [comment]
OK. 

But for the next tasks please open a separate issue for each task and track progress there (e.g. link pull requests or commits). Moreover, the wiki pages do not contain many details, at least try to add a screenshot about the final output and a summary paragraph about what have you achieved
